[theme]
# Base podrá ser "light" (claro) o "dark" (oscuro)
base="light"

# (Opcional) Personaliza colores según tu branding
primaryColor="#1F77B4"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"

# (Opcional) Font: "sans serif", "serif" o "monospace"
font="sans serif"
